# Generated by Django 4.0.4 on 2022-05-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=255)),
                ('productimage', models.ImageField(blank=True, upload_to='MoreImage')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('purchase_price', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(max_length=255)),
                ('offer_price', models.CharField(blank=True, max_length=255, null=True)),
                ('deliverycharge', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('colour', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255)),
                ('fake_order_sold', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='ProductImage')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApp.productcategory')),
            ],
        ),
    ]
