# Generated by Django 4.0.4 on 2022-05-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0003_productcolours_productsizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='size',
        ),
        migrations.DeleteModel(
            name='Productcolours',
        ),
        migrations.DeleteModel(
            name='ProductSizes',
        ),
    ]
