# Generated by Django 4.0.4 on 2022-05-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0004_remove_productmodel_colour_remove_productmodel_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allcolour', models.TextField()),
            ],
        ),
    ]
