# Generated by Django 4.0.4 on 2022-05-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0006_delete_testtable_productmodel_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
