# Generated by Django 4.0.4 on 2022-05-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=255)),
                ('clientname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('product_code', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.CharField(max_length=255)),
                ('deliverycharge', models.CharField(max_length=255)),
                ('product_VAT', models.CharField(max_length=255)),
                ('product_total', models.CharField(max_length=255)),
                ('product_size', models.CharField(max_length=255)),
                ('product_colour', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
