# Generated by Django 4.0.4 on 2022-05-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0003_ordermodel_userrandomid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
