# Generated by Django 4.0.4 on 2022-05-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0008_alter_ordermodel_product_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='product_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
