# Generated by Django 4.0.4 on 2022-05-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0010_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='details',
            field=models.CharField(default='', max_length=255),
        ),
    ]
