# Generated by Django 4.0.4 on 2022-05-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0012_alter_ordermodel_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingorder',
            name='colour',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='missingorder',
            name='quantity',
            field=models.CharField(blank=True, default=1, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='missingorder',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
