# Generated by Django 4.0.4 on 2022-05-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0013_missingorder_colour_missingorder_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingorder',
            name='userrandomid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
